version: '4.12.0'
services:
  php-apache-environment:
    container_name: php-side
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: database
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: company_info
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
      - 9906:3306
    volumes:
     - ./sql:/docker-entrypoint-initdb.d

